### ISSUE TITLE
Hardware final?

### ISSUE THREAD

**Issue by KeLaiFu** [zlosynth/kaseta#2]
I'm considering getting a few daisy boards and found your 2 projects, which both look great. Could you confirm if the hardware is finalized (for kaseta and achordian) before I throw my money at thonk?

Awesome looking modules and thanks for sharing them 👍👍👍

**Comment by phoracek** [comment]
Hey! I'm happy you like my modules. I consider hardware of both of them done. I don't plan any changes to their schema or layout at the moment. If there ever would be any modifications to them, they would be backwards compatible.

**Comment by KeLaiFu** [comment]
thanks for the reply, that's great news. I will get the iron warmed up!
